# Generated by Django 4.1.2 on 2023-01-04 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='producer',
            field=models.OneToOneField(default='exit', on_delete=django.db.models.deletion.CASCADE, related_name='producer', to='new.producer'),
            preserve_default=False,
        ),
    ]
