# Generated by Django 4.1.2 on 2023-01-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_remove_song_producer_delete_producer'),
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('colours', models.CharField(choices=[('BL', 'BLACK'), ('BR', 'BROWN'), ('CHOWK', 'CHOOKLET')], max_length=100)),
            ],
        ),
    ]
